CREATE TABLE USER_ACCOUNT_TABLE(
	USER_ID INTEGER,
	USER_NAME VARCHAR(255) NOT NULL,
	USER_APP_NAME VARCHAR(255) NOT NULL,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY (USER_ID)
);


CREATE TABLE USER_HISTORY_FOR_PREFERENCE_DATA_TEMP_TABLE(
	USER_ID INTEGER,
	RELEVANT_TERMS_BLOB TEXT,
	CONSTRAINT USER_ACCOUNT_TABLE_USER_ID_FK1 FOREIGN KEY (USER_ID)
	REFERENCES USER_ACCOUNT_TABLE (USER_ID)
);


CREATE TABLE ANONYMIZED_USER_CLASS_AND_CLUSTER_TABLE(
	USER_ID INTEGER NOT NULL,
	CLASS_NAME VARCHAR(255) NOT NULL,
	CLUSTER_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT USER_ACCOUNT_TABLE_USER_ID_FK2” FOREIGN KEY (USER_ID)REFERENCES USER_ACCOUNT_TABLE (USER_ID)
);


CREATE TABLE GLOBAL_CLASS_AND_CLUSTER_TABLE(
	CLASS_NAME VARCHAR(255) NOT NULL,
	CLUSTER_NAME VARCHAR(255) NOT NULL,
	CLASS_TERMS TEXT,
	CLUSTER_TERMS TEXT
);


CREATE TABLE AIRLINE_DATA_TABLE(
	AIRLINE_ID INTEGER,
	AIRLINE_NAME VARCHAR(255) NOT NULL,
	AIRLINE_NAME_ALIAS VARCHAR(255),
	IATA_CODE VARCHAR(5),
	ICAO_CODE VARCHAR(5),
	AIRLINE_CALLSIGN VARCHAR(255),
	COUNTRY_NAME VARCHAR(255),
	ACTIVE_STATUS VARCHAR(255)
);


CREATE TABLE AIRPORT_DATA_TABLE(
	AIRPORT_ID INTEGER,
	AIRPORT_NAME VARCHAR(255),
	CITY_NAME VARCHAR(255),
	COUNTRY_NAME VARCHAR(255),        
	IATA_CODE VARCHAR(255),
	ICAO_CODE VARCHAR(255),
	LATITUDE VARCHAR(255),
	LONGITUDE VARCHAR(255),
	ALTITUDE VARCHAR(255),
	TIMEZONE VARCHAR(255),
	DAY_LIGHT_SAVING_TIME VARCHAR(255),
	TIME_ZONE VARCHAR(255),
	TYPE VARCHAR(255),
	SOURCE VARCHAR(255)
);


CREATE TABLE AIRLINE_ROUTE_TABLE(
	AIRLINE_IATA_CODE_OR_ICAO_CODE VARCHAR(255),
	AIRLINE_ID VARCHAR(255),
	SOURCE_AIRPORT_IATA_CODE_OR_ICAO_CODE VARCHAR(255),
	SOURCE_AIRPORT_ID VARCHAR(255),
	DESTINATION_AIRPORT_IATA_CODE_OR_ICAO_CODE VARCHAR(255),
	DESTINATION_AIRPORT_ID VARCHAR(255),
	CODESHARE VARCHAR(255),
	STOPS_ON_THE_ROUTE VARCHAR(255),
	AIRPLANE_EQUIPMENT VARCHAR(255)
);

CREATE TABLE COUNTRY_CODE_TO_COUNTRY_NAME_TABLE(
	COUNTRY_CODE VARCHAR(5) NOT NULL,
	COUNTRY_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (COUNTRY_CODE)
);


CREATE TABLE STATE_CITY_TABLE (
	COUNTRY_CODE VARCHAR(5) NOT NULL,
	ASCII_CITY_NAME VARCHAR(255) NOT NULL,
	CITY_NAME VARCHAR(255) NOT NULL,
	REGION_NAME VARCHAR(255),
	POPULATION VARCHAR(255),
	LATITUDE VARCHAR(255),
	LONGITUDE VARCHAR(255),
	CITY_RANK INTEGER,
	CONSTRAINT STATE_CITY_TABLE_FK4 FOREIGN KEY (COUNTRY_CODE)
	REFERENCES COUNTRY_CODE_TO_COUNTRY_NAME_TABLE (COUNTRY_CODE)
);


CREATE TABLE GETAWAY_TABLE(
	GETAWAY_CATEGORY_ID INTEGER,
	GETAWAY_CATEGORY_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (GETAWAY_CATEGORY_ID)
);


CREATE TABLE DICTIONARY_DATASET_TABLE(
	GETAWAY_CATEGORY_ID INTEGER,
	SEASON_TERM  VARCHAR(255) NOT NULL,
	KEY_WORD_TERMS TEXT,
	CONSTRAINT DICTIONARY_DATASET_TABLE_GETAWAY_CATEGORY_ID_FK3 FOREIGN KEY (GETAWAY_CATEGORY_ID)
	REFERENCES GETAWAY_TABLE (GETAWAY_CATEGORY_ID) 
);


CREATE TABLE ATTRACTIONS_TABLE(
	COUNTRY_CODE VARCHAR(5) NOT NULL,
	COUNTRY_NAME VARCHAR(255) NOT NULL,
	CITY_NAME VARCHAR(255) NOT NULL,
	GETAWAY_CATEGORY_ID INTEGER,
	GETAWAY_CATEGORY_NAME VARCHAR(255) NOT NULL,
	ATTRACTION_NAME VARCHAR(255) NOT NULL,
	ATTRACTION_LOCATION VARCHAR(255) NOT NULL,
	ATTRACTION_DESCRIPTION TEXT,
	CONSTRAINT DICTIONARY_DATASET_TABLE_GETAWAY_CATEGORY_ID_FK2 FOREIGN KEY (GETAWAY_CATEGORY_ID) REFERENCES GETAWAY_TABLE (GETAWAY_CATEGORY_ID)
);


CREATE TABLE CRAWLER_DATA_FOR_GETAWAYS_TABLE(
	COUNTRY_CODE VARCHAR(5) NOT NULL,
	COUNTRY_NAME VARCHAR(255) NOT NULL,
	CITY_NAME VARCHAR(255) NOT NULL,
	GETAWAY_CATEGORY_ID INTEGER,
	START_DATE DATE,
	END_DATE DATE,
	ATTRACTION_NAME VARCHAR(255) NOT NULL,
	ATTRACTION_LOCATION VARCHAR(255),
	ATTRACTION_DESCRIPTION TEXT,
	INFO_BLOB TEXT,
	CONSTRAINT DICTIONARY_DATASET_TABLE_GETAWAY_CATEGORY_ID_FK7 FOREIGN KEY (GETAWAY_CATEGORY_ID) REFERENCES GETAWAY_TABLE (GETAWAY_CATEGORY_ID) 
);

CREATE TABLE CRAWLER_DATA_FOR_ROME2RIO_TABLE(
	START_COUNTRY_CODE VARCHAR(5) NOT NULL,
	START_COUNTRY_NAME VARCHAR(255) NOT NULL,
	START_CITY_NAME VARCHAR(255) NOT NULL,
	DEST_COUNTRY_CODE VARCHAR(5) NOT NULL,
	DEST_COUNTRY_NAME VARCHAR(255) NOT NULL,
	DEST_CITY_NAME VARCHAR(255) NOT NULL,
	MODES_OF_TRANSPORTATION TEXT,
	DURATION_FOR_EACH_MODE_OF_TRANSPORTATION TEXT,
	PRICE_RANE_FOR_EACH_MODE_OF_TRANSPORTATION TEXT
);

CREATE TABLE CRAWLER_DATA_HOTEL_FOR_PREDICTION_TABLE(
	COUNTRY_CODE VARCHAR(5) NOT NULL,
	COUNTRY_NAME VARCHAR(255) NOT NULL,
	CITY_NAME VARCHAR(255) NOT NULL,
	BOOKING_START_DATE DATE,
	BOOKING_END_DATE DATE,
	DAYS_REMAINING_TO_BOOKING_DATE INTEGER,
	HOTEL_LOCATION_ADDRESS VARCHAR(255),
	HOTEL_NAME VARCHAR(255) NOT NULL,
	HOTEL_RATING VARCHAR(255),
	PRICE_PER_DAY VARCHAR(255) NOT NULL,
	HOTEL_ROOM_TYPE VARCHAR(255),
	HOTEL_INFORMATION_META TEXT
);

CREATE TABLE CRAWLER_DATA_FLIGHTS_FOR_PREDICTION_TABLE(
	START_COUNTRY_CODE VARCHAR(5) NOT NULL,
	START_COUNTRY_NAME VARCHAR(255) NOT NULL,
	START_CITY_NAME VARCHAR(255) NOT NULL,
	START_AIRPORT_NAME VARCHAR(255)NOT NULL,
	START_IATA_CODE VARCHAR(255)NOT NULL,
	DEST_COUNTRY_CODE VARCHAR(5) NOT NULL,
	DEST_COUNTRY_NAME VARCHAR(255) NOT NULL,
	DEST_CITY_NAME VARCHAR(255) NOT NULL,
	DEST_AIRPORT_NAME VARCHAR(255)NOT NULL,
	DEST_IATA_CODE VARCHAR(255)NOT NULL,
	FLIGHT_BOOKING_START_DATE DATE, 
	FLIGHT_BOOKING_END_DATE DATE,
	DAYS_REMAINING_TO_BOOKING_DATE INTEGER,
	AIRLINE_NAME VARCHAR(255) NOT NULL,
	PRICE VARCHAR(255) NOT NULL,
	SEAT_CATEGORY VARCHAR(255),
	DAYSLENGTHOFSTAY INTEGER
);

CREATE TABLE ATTRACTIONS_TABLE_FROM_TRIPADVISOR(
	COUNTRY_NAME VARCHAR(255) NOT NULL,
	CITY_NAME VARCHAR(255) NOT NULL,
	ATTRACTION_NAME VARCHAR(255) NOT NULL,
	ATTRACTION_LOCATION VARCHAR(255) NOT NULL,
	ATTRACTION_DESCRIPTION TEXT,
	POPULARITY VARCHAR(50)
);